### ISSUE TITLE
simple script to train tf model

### ISSUE THREAD

**Issue by jwdinius** [minggli/fisheries-convnet#1]
This seems like great code, I'm just having a simple problem right now.  I have gotten all of the prerequisites installed on an AWS gpu-enabled machine via a conda environment, installed "app" as a python package via pip, and then I get a little stuck.  I was able to run the code in app/main.py after making some hacks in that file.  My question is simple: What is the simplest way to train your model; what are the command line arguments?  Thanks!

**Comment by minggli** [comment]
Hi, the app is written so you would need to run it as module. such as python3 -m app.main to train, python3 -m app.main eval to predict based on most recent checkpoint. Sorry there hasn't been much documentation around it.

That also would require data to be stored at correct location as set up in settings.py
